### ISSUE TITLE
error global install

### ISSUE THREAD

**Issue by crazyxhz** [Scout24-CH/styled-svg#15] opened 2019-03-12 12:54 UTC
`sudo npm i -g styled-svg`
get error message:
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hongzhi5/.npm/_logs/2019-03-12T12_50_08_048Z-debug.log
```
after clean cache force,
```
Unhandled rejection Error: EISDIR: illegal operation on a directory, open '/Users/hongzhi5/.npm/_cacache/tmp'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hongzhi5/.npm/_logs/2019-03-12T12_52_58_259Z-debug.log
```

**Comment by crazyxhz** [comment] 2019-03-12 12:54
error log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'styled-svg' ]
2 info using npm@6.8.0
3 info using node@v8.12.0
4 verbose npm-session 2f009d2d699cb20e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing npm Completed in 928ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>

```

**Comment by jaggli** [comment] 2019-03-22 17:05
thank you for reporting. will investigate

**Comment by jaggli** [comment] 2019-04-01 11:42
@crazyxhz I tried several things (downgrading to node 8.12.0 and npm v6.8.0, using NVM using MacOS, using Windows, also a co-worker tried to reproduce it.. we failed, we can't reproduce. 

Can you try to update npm to 6.9.0? maybe this helps..

I will close this, as long as we do not have more informations or more users suffering from this.

**Closed by jaggli** 2019-04-01 11:42 UTC
